// ChatGPT translation: ChatGPT's Skills feature uses the same SKILL.md
// convention as Claude — YAML frontmatter (name + description) plus a Markdown
// body and optional bundled resource folders, uploaded as a zip whose contents
// are a single top-level folder. So the port is each skill folder with the
// Claude-specific bits adapted out:
//
//   - ${CLAUDE_SKILL_DIR}/ routing        -> relative paths
//   - trailing "## Current request" + "$ARGUMENTS"  -> removed (Claude command tail)
//   - .claude-plugin/ manifests           -> omitted (Claude-only)
//
// tasks/ and references/ are already plain Markdown with relative links, so they
// are copied unchanged. Every skill under skills/ becomes its own bundle (ChatGPT
// uploads one zip per skill). Each bundle is validated before finishing.
//
// Output: dist/chatgpt/<skill>/ for each skill  (+ dist/chatgpt/README.md)

import { cpSync, existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const meta = {
  id: 'chatgpt',
  label: 'ChatGPT Skills',
  summary: 'Same SKILL.md format, Claude-specific routing adapted out.'
};

// Every directory under skills/ that has a SKILL.md, sorted for stable output.
function listSkills(skillsRoot) {
  if (!existsSync(skillsRoot)) return [];
  return readdirSync(skillsRoot)
    .filter((entry) => {
      const dir = join(skillsRoot, entry);
      return statSync(dir).isDirectory() && existsSync(join(dir, 'SKILL.md'));
    })
    .sort();
}

function adaptSkillMd(md) {
  let out = md;
  // Route by path relative to the skill root instead of the Claude variable.
  out = out.replace(/\$\{CLAUDE_SKILL_DIR\}\//g, '');
  // Drop the Claude plugin-command tail ("## Current request\n\n$ARGUMENTS").
  out = out.replace(/\n## Current request[\s\S]*$/, '\n');
  return out.trimEnd() + '\n';
}

function validateBundle(skillDir) {
  const problems = [];
  const skillMd = join(skillDir, 'SKILL.md');
  if (!existsSync(skillMd)) return [`missing SKILL.md in ${skillDir}`];
  const content = readFileSync(skillMd, 'utf8');

  if (!content.startsWith('---')) problems.push('SKILL.md must start with YAML frontmatter');
  if (!/^name:\s*.+$/m.test(content)) problems.push('SKILL.md missing name frontmatter');
  if (!/^description:\s*.+$/m.test(content)) problems.push('SKILL.md missing description frontmatter');
  if (content.includes('${CLAUDE_SKILL_DIR}')) problems.push('leftover ${CLAUDE_SKILL_DIR}');
  if (/\$ARGUMENTS/.test(content)) problems.push('leftover $ARGUMENTS');

  const refs = [
    ...content.matchAll(/`([^`]+?\.md)`/g),
    ...content.matchAll(/\]\(([^)]+?\.md)\)/g)
  ].map((m) => m[1]);
  for (const ref of refs) {
    if (!existsSync(join(skillDir, ref))) problems.push(`routes to missing file: ${ref}`);
  }
  return problems;
}

function writeReadme(outDir, skills) {
  const list = skills.map((s) => `- \`${s}/\``).join('\n');
  const zipLines = skills.map((s) => `zip -r ${s}.zip ${s}`).join('\n');
  const tree = skills
    .map((s) => `${s}/               ← a skill bundle (zip THIS folder)`)
    .join('\n');

  const md = `# HawkSoft skills for ChatGPT (generated)

Generated by \`npm run build\`. Do not edit — edit the source under \`skills/\` and
rebuild. Only the Claude-specific routing was changed; the procedures are identical.

## What's here

Each skill is its own bundle (ChatGPT uploads one zip per skill):

${list}

\`\`\`text
${tree}
\`\`\`

Every bundle has the same shape:

\`\`\`text
<skill>/
├── SKILL.md            ← frontmatter (name, description) + instructions
├── tasks/              ← one procedure per file
├── references/         ← shared standards and safety rules
└── screenshots/        ← visual context (add PNGs as they are captured)
\`\`\`

## Package them

ChatGPT expects a zip whose contents are a single top-level folder — so make one
zip per skill. From this directory:

\`\`\`bash
${zipLines}
\`\`\`

(On Windows: right-click a skill folder → “Compress to ZIP file”.)

## Upload them to ChatGPT

ChatGPT Skills use the same \`SKILL.md\` format as this repo, so no rewrite is
needed. Upload each zip as its own skill:

- **ChatGPT app** (Business, Enterprise, Healthcare, or Edu workspaces): open
  Settings, add a Skill, and upload the zip.
- **API:** \`POST /v1/skills\` with the zip as multipart form data (max 50 MB). The
  \`name\` and \`description\` come from the SKILL.md frontmatter.

Availability note: as of mid-2026, Skills are offered on ChatGPT Business,
Enterprise, Healthcare, and Edu. If your workspace lacks Skills, fall back to a
Project (upload the \`.md\` files as project files and paste the SKILL.md body as
the project instructions) or a Custom GPT (paste the SKILL.md body into
Instructions — note the 8,000-character limit — and upload the task/reference
files as Knowledge).

## Safety posture carries over

Verify the client, do not invent undocumented workflows, keep sensitive data out
of notes, and pause for approval before any final Save, Submit, Bind, Cancel, or
Delete. Test with fabricated data first.
`;
  writeFileSync(join(outDir, 'README.md'), md);
}

export function translate({ skillsRoot, outDir }) {
  const skills = listSkills(skillsRoot);
  if (!skills.length) throw new Error('No skills found under skills/.');

  const summary = [];
  for (const slug of skills) {
    const bundleDir = join(outDir, slug);
    cpSync(join(skillsRoot, slug), bundleDir, { recursive: true });

    const skillMdPath = join(bundleDir, 'SKILL.md');
    writeFileSync(skillMdPath, adaptSkillMd(readFileSync(skillMdPath, 'utf8')));

    const problems = validateBundle(bundleDir);
    if (problems.length) {
      throw new Error(`ChatGPT bundle "${slug}" failed validation:\n  - ${problems.join('\n  - ')}`);
    }
    summary.push(`${slug}/  —  ChatGPT Skill bundle (validated)`);
  }

  writeReadme(outDir, skills);
  summary.push(`${skills.length} skill bundle(s) — zip each folder separately; see dist/chatgpt/README.md`);
  return summary;
}
