// Claude translation: the native Claude Code plugin, in three activation
// variants. No content translation is needed (Claude is the source format); the
// "translation" is packaging plus per-variant description tuning and, for the
// strict variant, a bundled UserPromptSubmit hook.
//
// Output: dist/claude/<variant>/  (+ dist/claude/README.md)

import { cpSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const meta = {
  id: 'claude',
  label: 'Claude Code plugin',
  summary: 'Native plugin in three activation variants.'
};

const skillRel = 'skills/hawksoft-operations/SKILL.md';

// Front-loaded, wide-trigger description for the two auto-activating variants.
const AUTO_DESCRIPTION =
  'HawkSoft agency-management workflows. Use whenever HawkSoft is mentioned, or ' +
  'the user asks how to complete — or asks the assistant to perform — any HawkSoft ' +
  'operation such as logging phone calls or documenting client conversations. ' +
  'Currently covers logging inbound customer phone calls.';

const MANUAL_DESCRIPTION =
  'HawkSoft agency-management workflows (manual mode). Use only when the user ' +
  'explicitly invokes /hawksoft:hawksoft-operations or asks by name for a documented ' +
  'HawkSoft procedure. Do not auto-activate on incidental mentions of HawkSoft.';

const variants = [
  {
    id: 'hawksoft-always-enforce',
    label: 'Always enforce (strict)',
    blurb:
      'A bundled hook reminds the assistant to route through the skill every time ' +
      'HawkSoft is mentioned. Deterministic — closest to "always."',
    description: AUTO_DESCRIPTION,
    hook: true
  },
  {
    id: 'hawksoft-soft-trigger',
    label: 'Soft trigger (recommended default)',
    blurb:
      'A strong description auto-activates the skill on HawkSoft requests, but the ' +
      'assistant still decides. No hook, no extra setup.',
    description: AUTO_DESCRIPTION,
    hook: false
  },
  {
    id: 'hawksoft-manual',
    label: 'Manual only',
    blurb:
      'The skill activates only when the user explicitly runs ' +
      '/hawksoft:hawksoft-operations. No auto-trigger, no hook.',
    description: MANUAL_DESCRIPTION,
    hook: false
  }
];

function setDescription(skillMdPath, description) {
  const content = readFileSync(skillMdPath, 'utf8');
  if (!/^description:.*$/m.test(content)) {
    throw new Error(`No description frontmatter found in ${skillMdPath}`);
  }
  writeFileSync(skillMdPath, content.replace(/^description:.*$/m, `description: ${description}`));
}

function addHook(variantDir, guardScriptPath) {
  const hooksDir = join(variantDir, 'hooks');
  const scriptsDir = join(variantDir, 'scripts');
  mkdirSync(hooksDir, { recursive: true });
  mkdirSync(scriptsDir, { recursive: true });
  cpSync(guardScriptPath, join(scriptsDir, 'hawksoft-guard.mjs'));

  const hooksJson = {
    description:
      'Remind the assistant to use the hawksoft-operations skill whenever HawkSoft is mentioned.',
    hooks: {
      UserPromptSubmit: [
        {
          hooks: [
            {
              type: 'command',
              command: 'node "${CLAUDE_PLUGIN_ROOT}/scripts/hawksoft-guard.mjs"'
            }
          ]
        }
      ]
    }
  };
  writeFileSync(join(hooksDir, 'hooks.json'), JSON.stringify(hooksJson, null, 2) + '\n');
}

function writeIndex(outDir) {
  const rows = variants
    .map(
      (v) =>
        `## ${v.label}\n\n${v.blurb}\n\n` +
        'Install this folder:\n\n```text\n' +
        `claude --plugin-dir dist/claude/${v.id}\n` +
        '```\n'
    )
    .join('\n');

  const md =
    `# Choose a HawkSoft variant (Claude)\n\n` +
    `Generated by \`npm run build\`. Each subfolder is a complete, installable copy of ` +
    `the HawkSoft plugin tuned to a different activation behavior. Pick the one that ` +
    `matches how assertively you want the skill to engage, then install only that ` +
    `folder.\n\n${rows}\n` +
    `All three expose \`/hawksoft:hawksoft-operations\` and the same procedures — they ` +
    `differ only in how eagerly the skill activates. Install exactly one at a time.\n`;

  writeFileSync(join(outDir, 'README.md'), md);
}

export function translate({ repoRoot, outDir }) {
  const guardScript = join(repoRoot, 'scripts', 'hawksoft-guard.mjs');
  const summary = [];

  for (const v of variants) {
    const variantDir = join(outDir, v.id);
    mkdirSync(variantDir, { recursive: true });
    cpSync(join(repoRoot, '.claude-plugin'), join(variantDir, '.claude-plugin'), {
      recursive: true
    });
    cpSync(join(repoRoot, 'skills'), join(variantDir, 'skills'), { recursive: true });
    setDescription(join(variantDir, skillRel), v.description);
    if (v.hook) addHook(variantDir, guardScript);

    summary.push(`${v.id}  —  ${v.label}`);
    summary.push(`    install:  claude --plugin-dir dist/${meta.id}/${v.id}`);
  }

  writeIndex(outDir);
  summary.push('see dist/claude/README.md for the full comparison; install exactly one');
  return summary;
}
